config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users

  root "home#index"
  
  resources :groups do
    resources :entities, only: [:index, :new, :create]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
# app/models/entity.rb
class Entity < ApplicationRecord
  # belongs_to :author, class_name: 'User'
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities

  validates :name, presence: true, uniqueness: true
  validates :icon, presence: true
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Validaciones de Devise ya incluidas
  validates :name, presence: true, uniqueness: true

  has_many :groups
  has_many :entities, foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Redirección después de iniciar sesión
  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group

  def index
    @entities = @group.entities.order(created_at: :desc)
    @total_amount = @entities.sum(:amount)
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = @group.entities.build(entity_params)
    # @entity.author = current_user

    if @entity.save
      redirect_to group_entities_path(@group), notice: 'Transaction added successfully!'
    else
      render :new
    end
  end

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Not authorized to view this category.'
  end

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
# app/controllers/groups_controller.rb

class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @available_icons = ['fas fa-car', 'fas fa-home', 'fas fa-bicycle', 'fas fa-bus', 'fas fa-shopping-cart',
                        'fas fa-utensils', 'fas fa-plane', 'fas fa-money-bill-wave', 'fas fa-hamburger', 'fas fa-university']
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      redirect_to root_path, notice: 'Category created successfully!'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to groups_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entities/index.html.erb
<style>
body, html {
    margin: 0;
}

.container, .container-fluid, .container-xxl, .container-xl, .container-lg, .container-md, .container-sm {
    padding-right: 0;
    padding-left: 0;
}

.mt-4 {
  margin-top: 0 !important;
}

.container {
    display: flex;        
    flex-direction: column; 
    min-height: 100vh;     
    padding-right: 0;
    padding-left: 0;
}

.table-responsive {
    flex: 1 1 auto; 
    overflow-y: auto;        
}

.footer-logo {
    flex-shrink: 0;
    align-self: flex-end;
    margin-top: auto;
    margin-bottom: 20px;
    padding: 20px 0;
}

.navbar {
    width: 100%;
}

.login-nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%
}

.login-nav span, .navbar-brand, .login-btn {
    font-family: 'Proxima Nova', sans-serif;
    font-weight: bold;
    color: white;
}

.navbar-text {
    justify-content: center;
    margin: 0;
    margin-left: 70px;
    flex-grow: 1;
    text-align: center;
}

.login-btn {
    background: none;
    border: none;
    text-decoration: none;
}

a {
    text-decoration: none;
    color: lightgray;
    text-align: center;
    align-items: center;
    margin: 0 10px; 
    font-family: 'Proxima Nova', sans-serif;
}

.centered-links {
    position: fixed;
    bottom: 10px;
    left: 0;
    right: 0;
    width: 30px;
    margin-left: auto;
    margin-right: auto;
}

.centered-links a {
    pointer-events: auto;
}

.form-wrapper {
    margin-top: 20px;
}

.form-control {
    width: 100%;
    font-size: 16px;
    padding: 12px 20px;
    border: 1px solid lightgray;
}

.btn-primary {
    font-size: 16px;
    padding: 12px 20px;
}

.category-block {
    border: 1px solid lightgray;
    padding: 15px;
    margin: 10px 0;
    display: flex;
    flex-direction: column;
    align-items: center;
}

.category-block i {
    font-size: 24px;
    margin-bottom: 10px;
}

.category-details {
    display: flex;
    justify-content: space-between;
    width: 100%
}

.category-link {
    text-align: center;
    width: 100%;
    margin-top: 15px;
}

.horizontal-center {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 20px; 
    margin-top: 30px; 
    margin-bottom: 20px;
}


.main-logo {
    position: absolute;
    bottom: -150px;
    right: 160px;
    width: 70px;
    height: auto;
}

.btn-primary {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 90px;
    position: fixed;
    bottom: 0;
    left: 100;
    z-index: 1000;
    background-color: #5fb523;
    color: white;
    border: none;
    text-align: center;
}

.btn-primary::before {
    content: ''; 
    position: absolute; 
    top: 12px;
    left: 15px;
    right: 15px;
    bottom: 12px;
    border: 1.1px solid white;
}


.icon-list {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
    justify-content: center;
}

.icon-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: 5px;
    padding: 10px;
    border: 1px solid #e0e0e0;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.icon-item:hover {
    background-color: #f2f2f2;
}

.form-control {
    width: 100%;
    font-size: 16px;
    padding: 12px 20px;
    border: none;
    border-radius: 0;
    box-shadow: none;
    background-color: #f3f3f3;
    box-sizing: border-box;
}

.form-group {
    margin-bottom: 20px;
}

.form-group.mt-4 {
    text-align: center;
    position: fixed;
    right: 160px;
}

.table {
    border-collapse: collapse;
    margin-top: 20px;
    width: 100%;
    box-shadow: 0 5px 10px rgba(0,0,0,0.1);
    font-family: 'Proxima Nova', sans-serif;
}

.table th, .table td {
    padding: 15px 20px;
}

.table thead {
    background-color: #f4f4f4;
    color: #lightgray;
}

.table tbody tr:hover {
    background-color: #f4f4f4;
}

h3.text-center {
    display: flex;
    justify-content: center;
    font-size: 24px;
    padding: 10px 0;
    background-color: #f7f7f7;
    border-bottom: 1px solid #e0e0e0;
    border-top: 1px solid #e0e0e0;
    font-family: 'Proxima Nova', sans-serif;
}

.btn-secondary {
  position: fixed;
  right: 170px;
  background-color: #3778c2;
  border: none;
}

.back-btn-top-left {
    position: absolute;
    top: 14px;
    right: 340px;
    font-size: 24px;
    text-decoration: none;
}

</style>
<div class="container">
    <nav class="navbar navbar-expand-lg" style="background-color: #3778c2; padding: 20px 0">
        <div class="login-nav">
            <span class="navbar-text">
                Transactions: <%= @group.name %>
            </span>
            <% if user_signed_in? %>
                <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "login-btn" %>
            <% end %>
        </div>
    </nav>

    <h3 class="text-center mt-4">Total: $ <%= @total_amount %></h3>

    <div class="table-responsive mt-4">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <% @entities.each do |entity| %>
                    <tr>
                        <td><%= entity.name %></td>
                        <td><%= entity.amount %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <!-- Botones después de la tabla -->
    <div class="horizontal-center">
        <%= link_to 'ADD NEW TRANSACTION', new_group_entity_path(@group), class: 'btn btn-primary mt-1' %>
        <%= link_to '<', root_path, class: "btn btn-secondary back-btn-top-left" %>
    </div>
    
    <div class="footer-logo">
    <img src="<%= asset_path 'actions-logo-noback.PNG' %>" alt="Actions App Logo" class="main-logo">
</div>
</div>

app/views/entities/new.html.erb
<style>
body, html {
  margin: 0;
   }

   .container, .container-fluid, .container-xxl, .container-xl, .container-lg, .container-md, .container-sm {
    padding-right: 0;
    padding-left: 0;
}

.mt-4 {
  margin-top: 0 !important;
}

  .navbar {
  width: 100%;
   }

  .login-nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%;
  }

  .login-nav span,
  .navbar-brand,
  .login-btn {
      font-family: 'Proxima Nova', sans-serif; 
      font-weight: bold; 
      color: white; 
  }

  .navbar-brand {
      font-size: 24px; 
      text-decoration: none;
  }

  .navbar-text {
    justify-content: center;
    margin: 0;
    margin-left: 70px;
    flex-grow: 1;
    text-align: center;
}

  .login-btn {
      background: none; 
      border: none; 
      text-decoration: none; 
  }

   a {
      text-decoration: none; 
      color: lightgray;
      text-align: center; 
      align-items: center; 
      margin: 5px 10px;
      font-family: 'Proxima Nova', sans-serif;

   }

   .horizontal-center {
    position: fixed;
    bottom: 10px;
    left: 0;
    right: 0;
    width: 30px;
    margin-left: auto;
    margin-right: auto;
}

.horizontal-center a {
  pointer-events: auto;
}

.form-wrapper {
margin-top: 20px; 
}

      .form-control {
          width: 100%;
          font-size: 16px;
          padding: 12px 20px;
          border: 1px solid lightgray;  
      }
      
      .btn-primary {
          font-size: 16px;
          padding: 12px 20px;
      }

    .category-block {
        border: 1px solid lightgray;
        padding: 15px;
        margin: 10px 0;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .category-block i {
        font-size: 24px;
        margin-bottom: 10px;
    }

    .category-details {
        display: flex;
        justify-content: space-between;
        width: 100%
    }

    .category-link {
        text-align: center;
        width: 100%
        margin-top: 15px;
    }

    .horizontal-center {
    display: flex;
    justify-content: center;
    margin-bottom: 20px;  
}

.main-logo {
    position: fixed;
    bottom: 10px;
    right: 160px;
    width: 70px; 
    height: auto;
}

.btn-primary {
    background-color: #5fb523;
    color: #fff;
    border: none;
    border-radius: 5px;
    width: 100%;
    max-width: 300px;
    display: block;
    text-align: center;
}

.icon-list {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
    justify-content: center;
}

.icon-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: 5px;
    padding: 10px;
    border: 1px solid #e0e0e0;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.icon-item:hover {
    background-color: #f2f2f2;
}

.form-control {
    width: 100%;
    font-size: 16px;
    padding: 12px 20px;
    border: none;  
    border-radius: 0;  
    box-shadow: none;  
    background-color: #f3f3f3;  
    box-sizing: border-box; 
}

.form-group {
    margin-bottom: 20px; 
}

.container {   
    position: relative;
}

.form-group.mt-4 {
    text-align: center;
    position: fixed;
    right: 160px;
}
.btn-secondary {
  position: fixed;
  right: 170px;
  background-color: #3778c2;
  border: none;
}

.back-btn {
    position: absolute;
    right: 330px;
    top: 40%;
    transform: translateY(-50%);
    margin-left: 10px;
    font-size: 24px;
    text-decoration: none;
}


</style>

<div class="container">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg" style="background-color: #3778c2; padding: 20px 0">
    <div class="login-nav">
        <%= link_to '<', group_entities_path(@group), class: "btn btn-secondary back-btn" %>
        <span class="navbar-text">
            New transaction: <%= @group.name %>
        </span>
        <% if user_signed_in? %>
            <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "login-btn" %>
        <% end %>
    </div>
</nav>


    <!-- Formulario -->
    <div class="form-wrapper">
        
    <%= form_with model: [@group, @entity], html: { class: 'mt-4' } do |form| %>
        <div class="form-group">
            <%= form.text_field :name, class: 'form-control', placeholder: "Transaction's name", style: "color: black;" %>
        </div>
    
        <div class="form-group">
            <%= form.number_field :amount, class: 'form-control', placeholder: "Amount", style: "color: black;" %>
        </div>

            <div class="form-group mt-4">
                <%= form.submit "Save", class: 'btn btn-primary' %>
            </div>
        <% end %>
  
    </div>

    <!-- Logo -->
    <img src="<%= asset_path 'actions-logo-noback.PNG' %>" alt="Actions App Logo" class="main-logo">
</div>

app/views/groups/index.html.erb
<style>
body, html {
  margin: 0;
   }

   .container, .container-fluid, .container-xxl, .container-xl, .container-lg, .container-md, .container-sm {
    padding-right: 0;
    padding-left: 0;
}

.mt-4 {
  margin-top: 0 !important;
}


   .container {
    position: relative;
    min-height: 119vh;  
}


  .navbar {
  width: 100%;
   }

  .login-nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%
  }

  .login-nav span,
  .navbar-brand,
  .login-btn {
      font-family: 'Proxima Nova', sans-serif; 
      font-weight: bold; 
      color: white;
  }

  .navbar-brand {
      font-size: 24px; 
      text-decoration: none;
  }

  .navbar-text {
    justify-content: center;
    margin: 0;
    margin-left: -17px;
    flex-grow: 1;
    text-align: center;
}

  .login-btn {
      background: none;
      border: none; 
      text-decoration: none;
  }

   a {
      text-decoration: none; 
      color: lightgray; 
      text-align: center; 
      align-items: center; 
      margin: 0 10px; 
      font-family: 'Proxima Nova', sans-serif;

   }

   .centered-links {
    position: fixed;
    bottom: 10px;
    left: 0;
    right: 0;
    width: 30px;
    margin-left: auto;
    margin-right: auto;
}

.centered-links a {
  pointer-events: auto;    
}

.form-wrapper {
margin-top: 20px; 
}

      .form-control {
          width: 100%;
          font-size: 16px;
          padding: 12px 20px;
          border: 1px solid lightgray;  
      }
      
      .btn-primary {
          font-size: 16px;
          padding: 12px 20px;
      }

      .category-block {
        border: 1px solid lightgray;
        padding: 15px;
        margin: 10px 0;
        display: flex;
        flex-direction: column;
        align-items: center;
        flex: 1 1 auto;
        overflow-y: auto;
    }
    

    .category-block i {
        font-size: 24px;
        margin-bottom: 10px;
    }

    .category-block .category-details i {
    font-size: 30px;
    margin-top: 17px;
    margin-left: 12px;
}


    .category-details {
      display: flex;
      justify-content: space-between;
      align-items: center; 
      width: 100%;
      flex-direction: row; 
  }
  

    .category-link {
        text-align: center;
        width: 100%
        margin-top: 15px;
    }

    .horizontal-center {
    display: flex;
    justify-content: center;
    margin-bottom: 20px;  
}

.main-logo {
    position: absolute;
    bottom: -150px;
    right: 160px;
    width: 70px;
    height: auto;
}

.user-name {
    font-size: 15px; 
    margin-left: 20px; 
}

.btn-custom {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 90px;
    position: fixed;
    bottom: 0;
    left: 100;
    z-index: 1000;
    background-color: #5fb523;
    color: white;
    border: none;
    text-align: center;
}

.btn-custom::before {
    content: ''; 
    position: absolute; 
    top: 12px;
    left: 15px;
    right: 15px;
    bottom: 12px;
    border: 1.1px solid white;
}

.category-name {
  font-family: 'Proxima Nova', sans-serif;
  font-weight: 500;
  font-size: 20px;
}

.category-total {
  font-family: 'Proxima Nova', sans-serif;
  font-size: 20px;
  font-weight: 300;
}

.footer-logo {
    flex-shrink: 0;
    align-self: flex-end;
    margin-top: auto;
    margin-bottom: 20px;
    padding: 20px 0;
}

</style>

<div class="container">
    <nav class="navbar navbar-expand-lg" style="background-color: #3778c2; padding: 20px 0">
        <div class="login-nav">
        <span class="navbar-brand user-name">
        <%= current_user.name %>
    </span>
    
            <span class="navbar-text">
                Categories
            </span>
            <% if user_signed_in? %>
            <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "login-btn" %>
        <% end %>
        </div>
    </nav>

    <div class="mt-3">
        <% @groups.each do |group| %>
          <div class="category-block">
          <div class="category-details">
              <i class="<%= group.icon %>" aria-label="<%= group.name %> Icon"></i>
              <h3 class="category-name"><%= group.name %></h3>
              <p class="category-total">$ <%= group.entities.sum(:amount) %></p>
          </div>
          <div class="category-link">
              <%= link_to 'View Transactions', group_entities_path(group) %>
          </div>
      </div>
      
        <% end %>

        <!-- Utilizando la clase para centrar "Add a new category" -->
        <div class="horizontal-center">
        <%= link_to 'ADD CATEGORY', new_group_path, class: "btn btn-custom" %>

        </div>
    </div>
    <div class="footer-logo">
    <img src="<%= asset_path 'actions-logo-noback.PNG' %>" alt="Actions App Logo" class="main-logo">
</div>
</div>

app/views/groups/new.html.erb
<style>
body, html {
  margin: 0;
   }

   .container, .container-fluid, .container-xxl, .container-xl, .container-lg, .container-md, .container-sm {
    padding-right: 0;
    padding-left: 0;
}

.mt-4 {
  margin-top: 0 !important;
}


  .navbar {
  width: 100%;
   }

  .login-nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%;
  }

  .login-nav span,
  .navbar-brand,
  .login-btn {
      font-family: 'Proxima Nova', sans-serif; 
      font-weight: bold; 
      color: white; 
  }

  .navbar-brand {
      font-size: 24px; 
      text-decoration: none;
  }

  .navbar-text {
    justify-content: center;
    margin: 0;
    margin-left: 70px;
    flex-grow: 1;
    text-align: center;
}

  .login-btn {
      background: none; 
      border: none; 
      text-decoration: none; 
  }

   a {
      text-decoration: none; 
      color: lightgray; 
      text-align: center; 
      align-items: center; 
      margin: 5px 10px; 
      font-family: 'Proxima Nova', sans-serif;

   }

   .centered-links {
    position: fixed;
    bottom: 10px;
    left: 0;
    right: 0;
    width: 30px;
    margin-left: auto;
    margin-right: auto;
}

.centered-links a {
  pointer-events: auto; 
}

.form-wrapper {
margin-top: 20px;
}

      .form-control {
          width: 100%;
          font-size: 16px;
          padding: 12px 20px;
          border: 1px solid lightgray;  
      }
      
      .btn-primary {
          font-size: 16px;
          padding: 12px 20px;
      }

    .category-block {
        border: 1px solid lightgray;
        padding: 15px;
        margin: 10px 0;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .category-block i {
        font-size: 24px;
        margin-bottom: 10px;
    }

    .category-details {
        display: flex;
        justify-content: space-between;
        width: 100%
    }

    .category-link {
        text-align: center;
        width: 100%
        margin-top: 15px;
    }

    .horizontal-center {
    display: flex;
    justify-content: center;
    margin-bottom: 20px;  
}

.main-logo {
    position: absolute;
    bottom: -200px;
    right: 165px;
    width: 70px; 
    height: auto;
}

.btn-primary {
    background-color: #5fb523; 
    color: #fff;
    border: none;
    border-radius: 5px;
    width: 100%;
    max-width: 300px;
    display: block;
    text-align: center;
}

.icon-list {
    display: flex;
    flex-wrap: wrap;
    gap: 20px;
    justify-content: center;
}

.icon-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: 5px;
    padding: 10px;
    border: 1px solid #e0e0e0;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.icon-item:hover {
    background-color: #f2f2f2;
}

.form-control {
    width: 100%;
    font-size: 16px;
    padding: 12px 20px;
    border: none;  
    border-radius: 0;  
    box-shadow: none;  /* Elimina la sombra */
    background-color: #f3f3f3; 
    box-sizing: border-box; 
}

.form-group {
    margin-bottom: 20px; 
    font-family: 'Proxima Nova', sans-serif;
}

.form-group.mt-4 {
    text-align: center;
    position: fixed;
    right: 160px;
}
.btn-secondary {
  position: fixed;
  right: 170px;
  background-color: #3778c2;
  border: none;
}

.back-btn-top-left {
    position: absolute;
    top: 10px;
    right: 340px;
    font-size: 24px;
    text-decoration: none;
}

.footer-logo {
    position: relative;
    flex-shrink: 0;
    align-self: flex-end;
    margin-top: auto;
    margin-bottom: 20px;
    padding: 20px 0;
}

</style>

<div class="container">
    <nav class="navbar navbar-expand-lg" style="background-color: #3778c2; padding: 20px 0">
        <div class="login-nav">
            <span class="navbar-text">
                Add New Category
            </span>
            <% if user_signed_in? %>
            <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "login-btn" %>
            <% end %>
        </div>
    </nav>

    <div class="form-wrapper mt-3">

        <%= form_for @group, html: { class: 'mt-3' } do |f| %>
            <% if @group.errors.any? %>
                <div class="alert alert-danger">
                    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this category from being saved:</h2>
                    <ul>
                        <% @group.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="form-group">
            <%= f.text_field :name, class: 'form-control', placeholder: 'Name your new category' %>
        </div>
        

            <div class="form-group">
            <div class="horizontal-center">
            <%= f.label :icon, "Choose an icon" %>
        </div>
            <div class="icon-list">
                <% @available_icons.each do |icon| %>
                    <div class="icon-item">
                        <%= radio_button_tag 'group[icon]', icon, false, id: "icon_#{icon.gsub(' ', '_')}" %>
                        <%= label_tag "icon_#{icon.gsub(' ', '_')}", "<i class='#{icon} mr-1'></i>".html_safe %>
                    </div>
                <% end %>
            </div>
        </div>
        

            <div class="form-group mt-4">
                <%= f.submit "Save", class: 'mt-5 btn btn-primary' %>
            </div>
        <% end %>

        <!-- Utilizando la clase para centrar "Back" -->
        <div class="horizontal-center">
        <%= link_to '<', root_path, class: "btn btn-secondary back-btn-top-left" %>

        </div>
    </div>
    <div class="footer-logo">
    <img src="<%= asset_path 'actions-logo-noback.PNG' %>" alt="Actions App Logo" class="main-logo">
</div>
</div>

app/views/home/index.html.erb
<style>
    body {
        font-family: 'Arial', sans-serif; 
        margin: 0;
        padding: 0;
        background-color: #f9f9f9; 
    }
    .main-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }
    .main-logo {
        max-width: 200px;
        margin-bottom: 40px;
    }
    .main-title {
        font-size: 28px;
        margin-bottom: 10px;
        color: #333; 
    }
    .main-subtitle {
        font-size: 18px;
        margin-bottom: 40px;
        color: #777; 
        text-align: center;
    }
    .main-btn, .main-btn-outline {
        text-decoration: none;
    }
    .main-btn {
        width: 100%;
        max-width: 300px;
        margin-bottom: 15px;
        padding: 15px;
        font-size: 18px; 
        border-radius: 5px; 
        display: block;
        text-align: center;
    }
    .main-btn {
        background-color: #3778c2;
        color: #fff;
        border: none;
    }
    .main-btn-outline {
        background-color: transparent;
        color: #3778c2;
    }
</style>


<div class="main-container">
    <!-- Logo de la aplicación -->
    <img src="<%= asset_path 'actions-logo-noback.PNG' %>" alt="Actions App Logo" class="main-logo">

    <%= link_to "LOG IN", new_user_session_path, class: "btn btn-primary btn-lg main-btn" %>
    <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-outline-primary btn-lg main-btn main-btn-outline" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>